# Generated by Django 4.0.4 on 2022-04-26 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ishop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('clientPhoto', models.FileField(blank=True, default='', null=True, upload_to=ishop.models.userPhotoPath, verbose_name='photo')),
                ('clientName', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='first name')),
                ('clientSecondname', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='second name')),
                ('clientBirthday', models.DateTimeField(blank=True, null=True, verbose_name='birthday')),
                ('clientCity', models.EmailField(max_length=200, null=True, verbose_name='email')),
                ('clientAddress', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('slug', models.SlugField(null=True)),
                ('clientCountry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ishop.city', verbose_name='client')),
            ],
        ),
    ]
