# Generated by Django 4.0.4 on 2022-05-04 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ishop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyDescription', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=30, unique=True)),
                ('categorySlug', models.SlugField(null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksPhoto', models.FileField(blank=True, default='', null=True, upload_to=ishop.models.bookPhoto,
                                                verbose_name='photo')),
                ('booksTitle', models.CharField(max_length=100)),
                ('booksDiscription', models.CharField(default='', max_length=1700)),
                ('booksPrice', models.FloatField()),
                ('booksCount', models.IntegerField()),
                ('booksSlug', models.SlugField(blank=True, null=True, unique=True)),
                ('booksAuthor',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books',
                                   to='ishop.author', verbose_name='author')),
                ('booksGenre',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ishop.genre',
                                   verbose_name='books')),
                ('prod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='books',
                                              to='ishop.product')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Motoroils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motoroilsPhoto', models.FileField(blank=True, default='', null=True, upload_to=ishop.models.oilPhoto, verbose_name='photo')),
                ('motoroilsTitle', models.CharField(default='', max_length=200)),
                ('motoroilsDescription', models.CharField(default='', max_length=200)),
                ('motoroilsSlug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oilproducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oilproducer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepName', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='ishop.category', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Motoroilsvolums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motoroilsvolumsPrice', models.FloatField()),
                ('motoroilsvolumsCount', models.IntegerField()),
                ('motoroilsvolumsVolums', models.FloatField()),
                ('motoroilsvolums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oilvolume', to='ishop.motoroils')),
            ],
        ),
        migrations.AddField(
            model_name='motoroils',
            name='motoroilsProducer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oil', to='ishop.oilproducer'),
        ),
        migrations.AddField(
            model_name='motoroils',
            name='prod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oils', to='ishop.product'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('clientPhoto', models.FileField(blank=True, default='', null=True, upload_to=ishop.models.userPhotoPath, verbose_name='photo')),
                ('clientName', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='first name')),
                ('clientSecondname', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='second name')),
                ('clientBirthday', models.DateTimeField(blank=True, null=True, verbose_name='birthday')),
                ('clientEmail', models.EmailField(max_length=200, null=True, verbose_name='email')),
                ('clientAddress', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('slug', models.SlugField(null=True)),
                ('clientCountry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ishop.city', verbose_name='client')),
            ],
        ),
        migrations.CreateModel(
            name='Buy_step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buystepDatestart', models.DateTimeField(blank=True, null=True)),
                ('buystepDatefinish', models.DateTimeField(blank=True, null=True)),
                ('buystepBuy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ishop.buy', verbose_name='number order')),
                ('buystepStep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ishop.step', verbose_name='step')),
            ],
        ),
        migrations.CreateModel(
            name='Buy_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyproductCount', models.IntegerField(default=1, verbose_name='Count')),
                ('buyproductBuy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyproduct', to='ishop.buy', verbose_name='Number order')),
                ('buyproductProduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyproduct', to='ishop.product', verbose_name='buyproduct')),
            ],
            options={
                'verbose_name': 'Buy_product',
                'verbose_name_plural': 'Buy_products',
            },
        ),
        migrations.AddField(
            model_name='buy',
            name='buyClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy', to='ishop.client', verbose_name='client'),
        ),

    ]
