# Generated by Django 4.0.4 on 2022-04-26 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client',
            new_name='clientUser',
        ),
    ]
