# Generated by Django 4.0.4 on 2022-05-05 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoroils',
            name='prod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motoroils', to='ishop.product'),
        ),
    ]
