# Generated by Django 4.0.4 on 2022-05-11 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ishop', '0003_remove_books_id_remove_motoroils_id_alter_books_prod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentsbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combookDate', models.DateTimeField(auto_created=True)),
                ('combookText', models.CharField(max_length=200)),
                ('combookBooks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='ishop.books')),
                ('combookUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
