# Generated by Django 4.0.4 on 2022-05-11 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ishop', '0004_commentsbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='booksCom',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='StatusCommentsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuscomments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuscommentsblock', to='ishop.books')),
                ('statuscommentsBlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuscommentblock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikesBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likesbooksBooks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likesbook', to='ishop.books')),
                ('likesbooksUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likesbook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
