# Generated by Django 4.0.4 on 2022-05-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0005_books_bookscom_statuscommentsblock_likesbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsbook',
            name='combookDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
