# Generated by Django 4.0.4 on 2022-04-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0005_author_buy_category_genre_motoroils_oilproducer_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_step',
            name='buystepDatefinish',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
