# Generated by Django 4.0.4 on 2022-05-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0006_alter_commentsbook_combookdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientEmail',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='email'),
        ),
    ]
