# Generated by Django 4.0.4 on 2022-04-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0006_alter_buy_step_buystepdatefinish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_step',
            name='buystepDatefinish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
