# Generated by Django 4.0.4 on 2022-05-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0007_alter_client_clientemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clientMobile',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
