# Generated by Django 4.0.4 on 2022-04-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0007_alter_buy_step_buystepdatefinish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_step',
            name='buystepBuy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ishop.buy', verbose_name='number order'),
        ),
        migrations.AlterField(
            model_name='buy_step',
            name='buystepDatestart',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buy_step',
            name='buystepStep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ishop.step', verbose_name='step'),
        ),
    ]
