# Generated by Django 4.0.4 on 2022-04-28 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0008_alter_buy_step_buystepbuy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='buy_product',
            options={'verbose_name': 'Buy_product', 'verbose_name_plural': 'Buy_products'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categorys'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='id',
        ),
        migrations.AlterField(
            model_name='books',
            name='booksProduct',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='book', serialize=False, to='ishop.product'),
        ),
        migrations.AlterField(
            model_name='buy_product',
            name='buyproductBuy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyproduct', to='ishop.buy', verbose_name='buyproductBuy'),
        ),
    ]
