# Generated by Django 4.0.4 on 2022-05-19 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ishop', '0009_alter_motoroils_motoroilsproducer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentsoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comoilText', models.CharField(max_length=200)),
                ('comoilDate', models.DateTimeField(auto_now=True)),
                ('comoilOil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentOil', to='ishop.motoroils')),
                ('comoilUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentOil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
