# Generated by Django 4.0.4 on 2022-05-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0010_commentsoil'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_product',
            name='buyproductValue',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
