# Generated by Django 4.0.4 on 2022-04-28 13:22

from django.db import migrations, models

def step(apps, schema_editor):
    types = ['delivery', 'transporation', 'packege', 'payment']

    stepTypes = apps.get_model('ishop','Step')
    print(123333333)
    for i in types:
        st = stepTypes(stepName=i)
        st.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0012_alter_books_booksproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='booksSlug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.RunPython(step)
    ]
