# Generated by Django 4.0.4 on 2022-05-25 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0012_alter_buy_buyclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_step',
            name='buystepBuy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buystep', to='ishop.buy', verbose_name='number order'),
        ),
    ]
