# Generated by Django 4.0.4 on 2022-05-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0013_alter_buy_step_buystepbuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_step',
            name='buystepDatestart',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
