# Generated by Django 4.0.4 on 2022-04-30 11:16

from django.db import migrations, models
import django.db.models.deletion


def step(apps, schema_editor):
    types = ['delivery', 'transporation', 'packege', 'payment']

    stepTypes = apps.get_model('ishop', 'Step')
    print(123333333)
    for i in types:
        st = stepTypes(stepName=i)
        st.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ishop', '0013_alter_books_booksslug'),
    ]

    operations = [
        migrations.RunPython(step),
        migrations.AlterField(
            model_name='books',
            name='booksProduct',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                       related_name='commodity', serialize=False, to='ishop.product'),
        ),
        migrations.AlterField(
            model_name='books',
            name='booksSlug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='buy_product',
            name='buyproductBuy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyproduct',
                                    to='ishop.buy', verbose_name='Number order'),
        ),
        migrations.AlterField(
            model_name='buy_product',
            name='buyproductCount',
            field=models.IntegerField(default=1, verbose_name='Count'),
        ),
    ]
