# Generated by Django 4.0.4 on 2022-04-30 11:28

from django.db import migrations, models
import ishop.models

def step(apps, schema_editor):
    types = ['delivery', 'transporation', 'packege', 'payment']

    stepTypes = apps.get_model('ishop', 'Step')
    print(123333333)
    for i in types:
        st = stepTypes(stepName=i)
        st.save()


class Migration(migrations.Migration):

    dependencies = [

        ('ishop', '0014_alter_books_booksproduct_alter_books_booksslug_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='books',
            name='booksPhoto',
            field=models.FileField(blank=True, default='', null=True, upload_to=ishop.models.bookPhoto, verbose_name='photo'),
        ),
    ]
