# Generated by Django 4.0.4 on 2022-05-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0014_alter_buy_step_buystepdatestart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_step',
            name='buystepDatestart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
