# Generated by Django 4.0.4 on 2022-04-30 11:39

from django.db import migrations, models
import ishop.models


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0015_books_booksphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoroils',
            name='motoroilsDescription',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='motoroils',
            name='motoroilsPhoto',
            field=models.FileField(blank=True, default='', null=True, upload_to=ishop.models.bookPhoto, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='books',
            name='booksPhoto',
            field=models.FileField(blank=True, default='', null=True, upload_to=ishop.models.oilPhoto, verbose_name='photo'),
        ),
    ]
