# Generated by Django 4.0.4 on 2022-05-31 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ishop', '0015_alter_buy_step_buystepdatestart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckEmail',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='checkemail', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
