# Generated by Django 4.0.4 on 2022-05-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0016_checkemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkemail',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkemail',
            name='password',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
