# Generated by Django 4.0.4 on 2022-05-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0016_motoroils_motoroilsdescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clientCity',
            new_name='clientEmail',
        ),
    ]
