# Generated by Django 4.0.4 on 2022-05-03 13:01

from django.db import migrations, models
import ishop.models


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0017_rename_clientcity_client_clientemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genreName',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='motoroils',
            name='motoroilsPhoto',
            field=models.FileField(blank=True, default='', null=True, upload_to=ishop.models.oilPhoto, verbose_name='photo'),
        ),
    ]
