# Generated by Django 4.0.4 on 2022-06-02 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ishop', '0018_alter_checkemail_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyComOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to=settings.AUTH_USER_MODEL)),
                ('commentMain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='ishop.commentsoil')),
            ],
        ),
    ]
