# Generated by Django 4.0.4 on 2022-05-03 13:42

from django.db import migrations, models
import ishop.models


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0018_alter_genre_genrename_alter_motoroils_motoroilsphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='booksDiscription',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='books',
            name='booksPhoto',
            field=models.FileField(blank=True, default='', null=True, upload_to=ishop.models.bookPhoto, verbose_name='photo'),
        ),
    ]
