# Generated by Django 4.0.4 on 2022-06-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0019_replycomoil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomoil',
            old_name='comment',
            new_name='replyUser',
        ),
    ]
