# Generated by Django 4.0.4 on 2022-05-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0020_remove_motoroils_id_motoroils_motoroilproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motoroils',
            old_name='motoroilProduct',
            new_name='motoroilsProduct',
        ),
    ]
