# Generated by Django 4.0.4 on 2022-06-05 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0025_replycombooks_replyreplycombooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyreplycombooks',
            name='commentMain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replyreplybooks', to='ishop.replycombooks'),
        ),
    ]
